instance_deactivate_object (object40)
instance_deactivate_object (object47)
instance_deactivate_object (object48)
instance_deactivate_object (object38)
instance_deactivate_object (object41)
instance_deactivate_object (object49)
instance_deactivate_object (object50)
instance_create (view_xview[0]+480, view_yview[0]+224, object35)
instance_create (view_xview[0]+512, view_yview[0]+256, object54)
instance_create (view_xview[0]+512, view_yview[0]+352, object55)

