{
with (object36) instance_destroy ()
instance_create (object101,0,0)
with (object37) instance_destroy ()
with (object38) instance_destroy ()
with (object39) instance_destroy ()
with (object40) instance_destroy ()
with (object41) instance_destroy ()
with (object49) instance_destroy ()
with (object50) instance_destroy ()
with (object51) instance_destroy ()
with (object53) instance_destroy ()
with (object47) instance_destroy ()
with (object48) instance_destroy ()
with (object55) instance_destroy ()
with (object35) instance_destroy ()
instance_activate_object (object91)
instance_activate_object (object92)
instance_activate_object (object93)
instance_activate_object (object94)
instance_activate_object(object31)
instance_activate_object(cntrl)
instance_activate_object(object30)
instance_activate_object (object44)
instance_activate_object (lander)
instance_activate_object (dialcontrollerWIP)
instance_create (0, 0, object21)
}
